// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa-LF2s4YE_WIKbLDJVrOQ0xLGR0lUjPE',
    appId: '1:834729546603:web:59463db17ca382c7ba322e',
    messagingSenderId: '834729546603',
    projectId: 'axyojp-test-firebase-x-device',
    authDomain: 'axyojp-test-firebase-x-device.firebaseapp.com',
    storageBucket: 'axyojp-test-firebase-x-device.appspot.com',
    measurementId: 'G-JYS12T49YE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKY3bSYddml71BRhmjciyOINV6GRTIAW4',
    appId: '1:834729546603:android:80a6ccad12b6eb80ba322e',
    messagingSenderId: '834729546603',
    projectId: 'axyojp-test-firebase-x-device',
    storageBucket: 'axyojp-test-firebase-x-device.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYWq78BIJMdFUojaN4b9ckq34ds3yOMwQ',
    appId: '1:834729546603:ios:f33f94d9eb0769baba322e',
    messagingSenderId: '834729546603',
    projectId: 'axyojp-test-firebase-x-device',
    storageBucket: 'axyojp-test-firebase-x-device.appspot.com',
    iosClientId: '834729546603-u8polkf9c6dn2f2qk2dpelqgnt6ii4n4.apps.googleusercontent.com',
    iosBundleId: 'com.example.crossDeviceRemoteController',
  );
}
